export const MYROUTER_RESPONSE_HEADERS = {
  cache: "X-MyRouter-Cache",
  cacheHit: "X-MyRouter-Cache-Hit",
  compression: "X-MyRouter-Compression",
  costSaved: "X-MyRouter-Cost-Saved",
  decision: "X-MyRouter-Decision",
  fallbackAttempts: "X-MyRouter-Fallback-Attempts",
  latencyMs: "X-MyRouter-Latency-Ms",
  model: "X-MyRouter-Model",
  progress: "X-MyRouter-Progress",
  provider: "X-MyRouter-Provider",
  requestId: "X-MyRouter-Request-Id",
  responseCost: "X-MyRouter-Response-Cost",
  tokensIn: "X-MyRouter-Tokens-In",
  tokensOut: "X-MyRouter-Tokens-Out",
  version: "X-MyRouter-Version",
} as const;
